name: Bug report
description: Create a bug report to help us improve
title: "bug: <your title here>"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |

        Thank you for contributing to the improvement of Deltakit. Please fill out the following sections to report a bug.

        > [!NOTE] A bug is a disagreement between actual and documented behaviour, or an inaccurate error message.
        > Please file a [request from](https://github.com/Deltakit/deltakit/issues/new?template=request.md) if the
        > documentation does not define the expected behaviour, if you disagree with the documented behaviour, or if you
        > are asking for a new feature or performance improvement.
        > Please use the [test failure form](https://github.com/Deltakit/deltakit/issues/new?template=test_failure.yml)
        > if you're a contributor seeing a test failure in main, either locally or on CI.

  - type: checkboxes
    id: cla-signature
    attributes:
      label: Contributor License Agreement
      description: Please confirm the following before submitting
      options:
        - label: A Contributor Licence Agreement signature is required for any first PR contribution. Further information can be found in our [contributing guidelines](CONTRIBUTING.md).
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: |
        Please provide a succinct description of the observed behaviour.
    validations:
      required: true

  - type: textarea
    id: minimal-example
    attributes:
      label: Minimal Reproducible Example
      description: |
        Please provide a [Minimal Reproducible Example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
        as a copy-pastable code snippet if possible. If not, describe steps to
        reproduce the behaviour. Please enclose code blocks within triple backticks.
      placeholder: |
        ```python
        # Copy-pastable, executable code here
        ```

  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
      description: What actually happens. Please enclose code output / error messages within triple backticks.

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: What you expected to happen. Please cite (with links) relevant documentation about what should happen.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the bug reported here.
